/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice.swing.app;

import practice.swing.ex1.Exercise1;
import practice.swing.ex2.Exercise2;

public class App {
	public static void main(String[] args) {
		Exercise2.main(args);
	}
}
